# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OMDB

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReachabilitySwift'
  pod 'SwiftMessages'
  pod 'SDWebImage', '~> 5.0'
  pod 'SVProgressHUD'

  target 'OMDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OMDBUITests' do
    # Pods for testing
  end

end
